accent = "#FF1744"
cursor = "#FF1744"
foreground = "#FFE9ED"
background = "#090307"
selection_foreground = "#090307"
selection_background = "#FF1744"
color0 = "#090307"
color1 = "#FF1744"
color2 = "#B00020"
color3 = "#FF526F"
color4 = "#D50032"
color5 = "#FF1744"
color6 = "#FF6B81"
color7 = "#FFE9ED"
color8 = "#4A1825"
color9 = "#FF4569"
color10 = "#E00032"
color11 = "#FF8FA2"
color12 = "#FF1744"
color13 = "#FF6B81"
color14 = "#FFB3C0"
color15 = "#FFFFFF"
